### PR TITLE
Feature/firstpreview

### PR DESCRIPTION
**Pull request by SotoArmando**
ready for review!.

### CODE REVIEW

**Comment by SotoArmando** [comment]
> **Status: Changes Required**
> 
> Hello @SotoArmando ✋
> 
> The UI of the app looks good but you have to do few more things to get approval.
> 
> * [x]  You should configure linter in all of your project.Please check your pathwright for instructions.
> * [x]  It includes a rule for the node_modules directory and unecessary files like .DS_Store on .gitignore
> * [x]  It uses ES6 syntax
> * [x]  usage of arrow functions instead of the function keyword
> * [ ]  usage of import and export instead of require or module.exports
> * [ ]  proper usage of const and let keywords
> * [ ]  The application makes different requests for the Celsius data and the Fahrenheit data
> * [ ]  It has a toggle control to determine if the result will be shown in Celsius or Fahrenheit
> * [ ]   It uses either `promises` or `async/await` and It has error handling for promises or async/await
> * [ ]  No `console.log` commited to repo. It’s ugly, it kills performance. and it can make confidential data be visible in the browser tools.
> * [ ]  Keep all the styling logic in CSS files (If you need to change something like a background image, add the classes with the different backgrounds to the CSS and then change the class name attribute with JavaScript)
> * [ ]  Project should have a descriptive README file.
> 
> After making all this changes, check your app to see its working then submit for another review.
> 
> Happy Coding
> Adnan Afsari



> **Status: Changes Required**
> 
> Hello @SotoArmando ✋
> 
> The UI of the app looks good but you have to do few more things to get approval.
> 
> * [x]  You should configure linter in all of your project.Please check your pathwright for instructions.
> * [x]  It includes a rule for the node_modules directory and unecessary files like .DS_Store on .gitignore
> * [x]  It uses ES6 syntax
> * [x]  usage of arrow functions instead of the function keyword
> * [ ]  usage of import and export instead of require or module.exports
> * [ ]  proper usage of const and let keywords
> * [ ]  The application makes different requests for the Celsius data and the Fahrenheit data
> * [ ]  It has a toggle control to determine if the result will be shown in Celsius or Fahrenheit
> * [ ]   It uses either `promises` or `async/await` and It has error handling for promises or async/await
> * [ ]  No `console.log` commited to repo. It’s ugly, it kills performance. and it can make confidential data be visible in the browser tools.
> * [ ]  Keep all the styling logic in CSS files (If you need to change something like a background image, add the classes with the different backgrounds to the CSS and then change the class name attribute with JavaScript)
> * [ ]  Project should have a descriptive README file.
> 
> After making all this changes, check your app to see its working then submit for another review.
> 
> Happy Coding
> Adnan Afsari

Thanks for the review :). can i have a more detailed reference over: proper usage of const and let keywords and, It uses either `promises` or `async/await` and It has error handling for promises or async/await. as i was using just the google implementation (client side) for maps. and (server side) for weatherbit.

**Comment by AdnanAfsari** [comment]
Hello @SotoArmando 

- [ ] You should use let or const on your project and ignore var.

- [ ] You should use either promises or async/await and  catch error when making network request.

If you are still confused please reach out to Full Time TSEs.

Happy Coding 
Adnan Afsari

**Comment by SotoArmando** [comment]
Ahh srry, then how can i reach them?

**Comment by AdnanAfsari** [comment]
Hello @SotoArmando 

I really appreciate your hard work, Please make another request after fixing everything as we talked in our video call 😄 .

Happy Coding

Adnan Afsari

**Pull request merged**
